/**
 * Mirrors the shape of public/data/beaten_games.json, generated by the
 * scraper's beaten-games pipeline. `games` records whether an achievement
 * "story marker" was found for a title (and why not, when it wasn't);
 * `wins` records whether a specific member actually unlocked that marker.
 */

/** The achievement treated as evidence a game's main story was beaten. */
export interface BeatenGameMarker {
  apiname: string
  name: string
  description?: string
  /** Percent of all Steam owners who have unlocked this achievement. */
  global_percent: number
  source: string
  /** Steam Hunters' id for this achievement, when matched — links directly to it instead of the game's achievements page. */
  sh_achievement_id?: number
}

/** Why no story marker could be established for a game. */
export type NoMarkerReason =
  | 'package'
  | 'no_achievements'
  | 'no_marker_found'
  | 'schema_unavailable'

export interface BeatenGameEntry {
  marker: BeatenGameMarker | null
  no_marker_reason: NoMarkerReason | null
  story_tag_count?: number
  checked_at: string
  /**
   * Base-game app id, when this entry is for a DLC app resolved to its base
   * game's achievements. Present only for DLC entries; use it in place of
   * the giveaway's app id wherever the Steam achievements page is linked.
   */
  resolved_app_id?: number
}

/** Why a specific win couldn't be checked against its game's marker. */
export type NoDataReason =
  | 'profile_private'
  | 'no_stats'
  | 'marker_missing_from_player_data'

export interface BeatenWinEntry {
  beaten: boolean | null
  unlock_time: number | null
  no_data_reason: NoDataReason | null
  checked_at: string
}

/** public/data/beaten_games.json. `wins` is keyed by `<steamId>::<appId>`. */
export interface BeatenGamesData {
  last_updated: string
  /** Keyed by app id (as a string). */
  games: Record<string, BeatenGameEntry>
  /** Keyed by `<steamId>::<appId>`. */
  wins: Record<string, BeatenWinEntry>
}

/** Lookup key for `BeatenGamesData['wins']`. */
export function beatenWinKey(steamId: string, appId: number): string {
  return `${steamId}::${appId}`
}
