/**
 * Mirrors the shape of public/data/ipb_discord.json, generated by a sibling
 * scraper pipeline that matches "I Play Bro" submissions to their Discord
 * thread. `wins` links a win to the thread where it was discussed; threads
 * that couldn't be matched to any win are listed under `unmatched_threads`
 * so admins can spot submissions the matcher missed.
 */

export interface IpbDiscordWinEntry {
  thread_id: string
  url: string
  thread_name: string
  /** How this win was matched to its thread, when known. */
  matched_by?:
    | 'giveaway_link'
    | 'app_link'
    | 'review_link'
    | 'title'
    | 'title_unique'
    | 'app_link_unique'
  /** Steam review URL linked in the submission, when present. */
  review_url?: string
  /**
   * Whether the sheet's i_played_bro/required_play flag is set for this win.
   * The sheet flag is only set once a mod verifies the submission, so
   * `false` marks this win as awaiting verification — `wins` covers every
   * win matched to a thread, not just flagged ones.
   */
  win_flagged?: boolean
  owner_discord_name?: string
  /** ISO timestamp the Discord thread was created. */
  thread_created_at?: string
}

export interface IpbDiscordUnmatchedThread {
  thread_id: string
  name: string
  url: string
  owner_discord_name: string
}

/** public/data/ipb_discord.json. `wins` is keyed by `<steamId>::<giveawayLink>`. */
export interface IpbDiscordData {
  last_updated: string
  wins: Record<string, IpbDiscordWinEntry>
  unmatched_threads: IpbDiscordUnmatchedThread[]
}

/** Lookup key for `IpbDiscordData['wins']`. */
export function ipbDiscordWinKey(steamId: string, giveawayLink: string): string {
  return `${steamId}::${giveawayLink}`
}
