name: Update Website Data

on:
  schedule:
    # Run every 12 hours at 00:00 and 12:00 UTC
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Create and push empty commit
        run: |
          git commit --allow-empty -m "🔄 Trigger website build - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push origin ${{ github.ref_name }} 