name: Update Website Data

on:
  schedule:
    # Run every 8 hours at 00:00 and 12:00 UTC
    - cron: '0 0,8 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Update data
        run: pnpm run data

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "update data ${timestamp}"
          git push