name: Update Website Data

on:
  schedule:
    # Run every 8 hours at 00:00 and 12:00 UTC
    - cron: '0 0,8 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Update data
        run: pnpm run data

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add packages/website/public/data/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Update data - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push origin ${{ github.ref_name }}
          fi 
